---
title: 'Report: Wash data checks'
author: "Steve and Jonathan"
date: " `r as.Date(Sys.time())` "
output:
  html_document:
    fig_caption: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
---


```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE
	, warning = FALSE
	, message = FALSE
	, fig.width = 10
	, fig.height = 10
	, results = "asis")
options(width = 12)

library(ggplot2)
theme_set(theme_bw() +
	theme(panel.spacing=grid::unit(0,"lines")))
library(ggpubr)

library(dplyr)
library(DT)
library(scales)
library(dotwhisker)
library(ggstance)
library(corrplot)
library(lme4)
library(splines)

source("../funs/ggplot_theme.R")
source("../funs/effectsPlot.R")

load("washdataInspect.rda")
load("washTidyestimates.rda")
load("washPredEffects.rda")
```

## Variables

Distribution of missing cases for each of the variables. 
- Although `hungerscale` and `belowpovertyline` have more proportion of missing cases, `wealthindex` is used as a proxy for the two.

```{R}
nint <- nrow(wash_lagged_df)
summary_df <- (prevcases_df
	%>% group_by(nprev_miss1)
	%>% summarise(nn = sum(nprev_miss1))
)
datatable(miss_cases_df, rownames = FALSE)
```


- **Fixed effect variables**
	- `age`
	- `gender`
	- `slumarea` - Slum area (Korogocho or Viwandani)
	- `hhsize` - number of people living in the household as at survey
	- `wealthindex` - The wealth index was constructed using principle component analysis (PCA) with input as indicator variables on ownership of household and individual assets/items (such as TV, electricity, fridge, radio, bicycle, motorcycle, shoes, blanket, clothes, etc.), and nature of their housing
	- `StatusP` - Aavailability of service in the previous year (0/1)

- **Random effect variables**
	- `(services|hhid)` - correlated, time-independent variation among households
	- `(services|years)` - correlated, household-independent variation across years 

- **Response variables**

+-----------------------+-----------------------+-----------------------+
|                       | **Improved**          | **Unimproved**        |
+-----------------------+-----------------------+-----------------------+
|- **Drinking water     | -   Piped water into  | -   Unprotected dug   |
| source**              |     dwelling, plot or |     well              |
|                       |     yard              |                       |
|                       |                       | -   Unprotected       |
|                       | -   Public            |     spring            |
|                       |     tap/standpipe     |                       |
|                       |                       | -   Small water       |
|                       | -   Tube well /       |     vendor (cart with |
|                       |     borehole          |     small tank or     |
|                       |                       |     drum)             |
|                       | -   Protected dug     |                       |
|                       |     well with hand    | -   Bottled water     |
|                       |     pump              |                       |
|                       |                       | -   Tanker truck      |
|                       | -   Protected spring  |                       |
|                       |                       | -   Rainwater         |
|                       | -   Rainwater         |     collection from   |
|                       |     collection from   |     surface run off.  |
|                       |     the roof          |     Surface water     |
|                       |                       |     (river, dam,      |
|                       |                       |     lake, pond,       |
|                       |                       |     stream, canal,    |
|                       |                       |     irrigation        |
|                       |                       |     channels)         |
|                       |                       |                       |
|                       |                       | -   Protected dug     |
|                       |                       |     well with bucket  |
+-----------------------+-----------------------+-----------------------+
|- **Toilet facility    | -   Flush / pour      | -   Flush / pour      |
| type**                |     flush to piped    |     flush to          |
|                       |     sewer system or   |     elsewhere e.g. to |
|                       |     septic tank or    |     open drain        |
|                       |     pit latrine       |                       |
|                       |                       | -   Pit latrine       |
|                       | -   VIP latrine       |     without slab      |
|                       |                       |     (slab with holes) |
|                       | -   Pit latrine with  |     /open pit         |
|                       |     slab              |                       |
|                       |                       | -   Bucket            |
|                       | -   Composting toilet |                       |
|                       |                       | -   Hanging toilet /  |
|                       |                       |     hanging latrine   |
|                       |                       |                       |
|                       |                       | -   No facilities or  |
|                       |                       |     bush or field     |
+-----------------------+-----------------------+-----------------------+
|- **Garbage disposal   | -   Garbage dump      | -   In the river      |
| method**              |                       |                       |
|                       | -   Private pits      | -   On the road,      |
|                       |                       |     railway           |
|                       | -   Public pits       |     line/station      |
|                       |                       |                       |
|                       | -   Proper garbage    | -   In                |
|                       |     disposal services |     drainage/sewage/t |
|                       |                       | rench                 |
|                       | -   Other organized   |                       |
|                       |     groups such as    | -   Vacant/abandoned  |
|                       |     the national      |     house/plot/field  |
|                       |     youth service     |                       |
|                       |                       | -   No designated     |
|                       |                       |     place/all over    |
|                       |                       |                       |
|                       |                       | -   Street            |
|                       |                       |     boys/urchins      |
|                       |                       |                       |
|                       |                       | -   Burning           |
|                       |                       |                       |
|                       |                       | -   Other             |
+-----------------------+-----------------------+-----------------------+



## Data format choices

There two choices to be made:

- **Consecutive year interviews per household**: We assume that households conducted interviews every year. Consequently, a case missing an interview in the previous (immediate) year is droped (`r percent(sum(summary_df$nn/nint))`). See the Figure below. Model fitted based on this has a `_consec` tag.

```{R fig.width = 5, fig.height = 5}
print(ggplot(summary_df, aes(x = as.factor(nprev_miss1), y = nn))
	+ geom_bar(stat='identity')
	+ geom_text(aes(label=paste0(percent(nn/nint)))
		, stat='identity'
		, position=position_dodge(0.9)
		, vjust=-0.2
	)
	+ labs(x = "Missing consecutive interviews"
		, y = "No. of interviews"
	)
)
```

```{R}
summary_df2 <- (prevcases_df
	%>% filter(nprev_miss2 > 0)
	%>% group_by(nprev_miss2)
	%>% summarise(nn = sum(nprev_miss2))
)
```

- The `r percent(sum(summary_df$nn/nint))` includes first year (specific to household) cases which do not have the previous years. These are dropped by model matrix. Thus the proportion of interviews we are actually dropping due to missing previous (immediate) interviews is `r percent(sum(summary_df2$nn/nint))`.

```{R, fig.width = 5, fig.height = 5}
print(ggplot(summary_df2, aes(x = as.factor(nprev_miss2), y = nn))
	+ geom_bar(stat='identity')
	+ geom_text(aes(label=paste0(percent(nn/nint)))
		, stat='identity'
		, position=position_dodge(0.9)
		, vjust=-0.2
	)
	+ labs(x = "Missing consecutive interviews"
		, y = "No. of interviews"
	)
)
```

```{R}
summary_df3 <- (wash_lagged_df
	%>% group_by(hhid)
	%>% mutate(n = n()
		, nprev_miss1 = sum(is.na(watersourceP))
	)
	%>% ungroup()
	%>% mutate_at("hhid", as.numeric)
	%>% select(hhid, n, nprev_miss1)
	%>% distinct()
	%>% summarise(nn = sum(nprev_miss1))
)
```

- **Lagged interviews**: Any household interview (most recent) preceding the current household interview is considered consecutive interview. In this case, only interviews in the first year (household specific) will have missing previous year. Consequently, only first year interviews will be dropped (`r percent(summary_df3$nn/nint)`). Model fitted based on this has `_lagged` tag.

- **Thoughts**
	- Should we impute services for the previous year in the first year (household specific)?


## Estimates

```{R fig.width = 12, fig.height = 14}
estimates_df <- extract_coefs_df
parameters <- pull(estimates_df, parameter) %>% unique()
estimates_df <- (estimates_df
	%>% mutate(parameter = factor(parameter, levels = parameters, labels = parameters))
)

pos <- ggstance::position_dodgev(height=0.5)

print(ggplot(estimates_df 
	%>% filter(model != "lagged_vyears")
		, aes(x = estimate, y = term, colour = model)
	)
	+ geom_point(position = pos)
	+ ggstance::geom_linerangeh(aes(xmin = conf.low, xmax = conf.high), position = pos)
	+ scale_colour_brewer(palette="Dark2"
		, guide = guide_legend(reverse = TRUE)
	)
	+ geom_vline(xintercept=0,lty=2)
	+ labs(x = "Estimate"
		, y = ""
		, colour = "Model"
	)
	+ facet_wrap(~parameter, scale = "free", ncol = 2)
	+ facet_theme
	+ theme(legend.position = "bottom")
)

```

## Predictor effect plots


```{R}
#names(mod_effect_df) <- gsub(".*\\:|.*\\(|\\,.*", "", names(mod_effect_df))
service_df <- (data.frame(mod_effect_df[["services"]])[, c("services", "fit", "lower", "upper")]
	%>% group_by(services) 
	%>% summarise_at(vars(fit:upper), mean, na.rm = TRUE)
)
service_plot <- (ggplot(service_df, aes(x = services, y = fit))
	+ geom_point(size = 0.6)
	+ geom_errorbar(aes(ymin = lower, ymax = upper), width = 0)
	+ scale_x_discrete(limits = c("watersource", "garbagedposal", "toilettype"))
	+ labs(x = "Services"
		, y = "Probability of\nimproved service"
	)
)
```


```{R fig.height=8}
num_vars <- c("age"
	, "hhsize"
	, "year"
	, "wealthindex"
	, "statusP"
)
num_plots <- lapply(num_vars, function(x){plotEffects(mod_effect_df[[x]], x, x)})
ggarrange(service_plot
	, num_plots[[1]] + rremove("ylab")
	, num_plots[[2]] + rremove("ylab")
	, num_plots[[3]] #+ rremove("ylab")
	, num_plots[[4]] + rremove("ylab")
	, num_plots[[5]] + rremove("ylab")
	, common.legend = TRUE
	, legend = "bottom"
	, nrow = 2
	, ncol = 3
)
```

```{R fig.height = 8}
cat_vars <- c("slumarea", "gender")
cat_plots <- lapply(cat_vars, function(x){plotEffects(mod_effect_df[[x]], x, x)})
p1 <- (cat_plots[[1]]
   + theme(plot.margin = margin(0, 1, 0.1, 1, "cm")
      , panel.spacing.x = unit(1, "lines")
   )
)
p2 <- (cat_plots[[2]]
	+ theme(plot.margin = margin(0, 1, 0.1, 1, "cm")
		, panel.spacing.x = unit(1, "lines")
	)
)
ggarrange(p1 #+ rremove("ylab")
	, p2 #+ rremove("ylab")
	, nrow = 3 
	, ncol = 1
)
```

```{R fig.width=8, fig.height=8, fig.align="center"}
#varcorrPlot <- function(modObj){
#	varcorr <- VarCorr(modObj)
#	varcorr <- varcorr$hhid
#	colnames(varcorr) <- gsub("services", "", colnames(varcorr))
#	rownames(varcorr) <- gsub("services", "", rownames(varcorr))
#	corrplot.mixed(cov2cor(varcorr), upper = "ellipse", tl.cex = 0.6)
#}
#par(mfrow=c(1,2))
#varcorrPlot(glmer_model_lagged)
#varcorrPlot(glmer_model_consec)
```
