---
title: 'Report: Wash data analysis'
author: "Steve and Jonathan"
date: " `r as.Date(Sys.time())` "
output:
  html_document:
    fig_caption: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
---


```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE
	, warning = FALSE
	, message = FALSE
	, fig.width = 10
	, fig.height = 10
	, results = "asis")
options(width = 12)

library(ggplot2)
theme_set(theme_bw() +
	theme(panel.spacing=grid::unit(0,"lines")))

library(forcats)
library(ggpubr)

library(dplyr)
library(DT)
library(scales)
library(dotwhisker)
library(ggstance)
library(corrplot)
library(lme4)
library(splines)

source("../funs/ggplot_theme.R")
source("../funs/effectsPlot.R")

load("washPredEffects_plots.rda")
load("washdataInspect_plots.rda")
load("washEffectsize_plots.rda")
```

## Service in the previous year computation

- Grouped within the households
- Service status for the immediate preceding year is considered i.e., for every household, we count the number of interviews (services) missed in the immediate preceding year based on the current interview year.
	- This is not based on supposed study period total number of interviews per household ($14$) but rather the total number of interviews conducted in that specific household during the study period.
		- For example, in the Table below, household 1 had 3 interviews with 1 missing previous interview (`nprev_miss1`). `nprev_miss1` counts all missing previous year interviews including the first year while `nprev_miss2` exludes the first year. On the other hand, household 3 had a total of 11 interviews, 2 missing previous interviews i.e.,  one being the first year interview while the other being the year preceding (year 3) year 4 interview. Note: year 2 is also missing but we ignore that because year 4 is the current observational year.


```{R}
datatable(prevcases_df_summary, rownames = FALSE, options = list(pageLength = 8))
```

- We sum up the number of previous year missing interviews for each missing category. For example, in HH 1 there is 1 interview missing in the previous year, we sum up all interviews missing 1 interview in the previous and do the same for the rest of the categories ($2,3,4,...$), etc. The distribution of **total** number of interviews with missing immediate previous year are shown in the Figure below.
- Including the first year, `r percent_miss_consec` have missing previous interviews. 
- The denominator for the percentages is the total number of all interviews, including year 1 (reason to aggregate by total number of interviews per category as opposed to frequency)

```{R fig.width = 5, fig.height = 5}
print(consec_all_plot)
```

- Ignoring the first year interviews (`r percent_year0` which are modeled separately), the proportion of interviews we are actually dropping due to missing preceding year interviews are `r percent_miss_consec_noyr0 `(about `r percent_miss_consec_noyr0_all` of all the interviews).

```{R, fig.width = 5, fig.height = 5}
print(consec_noyr0_plot)
```

## Distribution of services

- The Figure below shows the proportion of households with improved services over years. The dotted lines represent the household average for each service over the entire study period.


```{R distributions1, fig.width = 7, fig.height = 8}
print(prop_plot)
```

### No. of interviews completed by HH

- If every household was interviewed per year, we would expect $14$ interviews per household. On the contrary, over $40\%$ of the households only had $1$ interview over the entire study period.
- Denominator is number of HH (expected number of interviews per year)

```{R fig.width = 7, fig.height = 5}
print(n_interviews_plot)
```

### No. of interviews per year

- The Figure below shows the percentage of interviews per year.
	- We may need to seek for clarification on low percentage in $2003$ 

```{R fig.width = 7, fig.height = 5}
print(year_plot)
```

### Current vs previous year service status (JD: Status Quo?)

- We track service transitions from the previous year to the current year (within households):
	- **All -**: Service not improved both in the previous and in the current year
	- **All +**: Improved service both in the previous and current year
	- **No prev.**: Had no service in the previous year (missing interview in the previous year)
	- **Gain**: Unimproved service in the previous year but improved service in the current year
	- **Loss**: Improved service in the previous year but unimproved service in the current year

```{R}
print(status_quo_plot)
```

### Household size scaling

- I wasn't sure why I still hard large value after scaling. 
- Do we need to scale household size?
- Should we think of back transforming the predictor effects from effect plots? Is this something sensible?

```{R}
print(hhsize_plot)
```



## Variables

Distribution of missing cases per variable is shown in the table below

- A total of `r nint_all` were done between $2002 - 2015$.
- There are `r nhhid` households, each interviewed once for every interview year
- Not all households had interviews conducted every year
- Although `hungerscale` and `belowpovertyline` have more proportion of missing cases, `wealthindex` is considered a good proxy for the two.

```{R missingness}
datatable(miss_cases_df, rownames = FALSE)
```

- Variables with missing cases are not currently included in the model. A mixed model, `glmer`, with:

- **Fixed effect variables**
	- `age`
	- `gender`
	- `slumarea` - Slum area (Korogocho or Viwandani)
	- `hhsize` - number of people living in the household as at survey
	- `wealthindex` - The wealth index was constructed using principle component analysis (PCA) with input as indicator variables on ownership of household and individual assets/items (such as TV, electricity, fridge, radio, bicycle, motorcycle, shoes, blanket, clothes, etc.), and nature of their housing
	- `StatusP` - Availability of service in the previous year (0/1)

- **Random effect variables**
	- `(services-1|hhid)`
	- \*`(services-1|hhid/years)` - We can talk about this and how much complexity we need (not implemented)

- **Response variables**

+-----------------------+-----------------------+-----------------------+
|                       | **Improved**          | **Unimproved**        |
+-----------------------+-----------------------+-----------------------+
|- **Drinking water     | -   Piped water into  | -   Unprotected dug   |
| source**              |     dwelling, plot or |     well              |
|                       |     yard              |                       |
|                       |                       | -   Unprotected       |
|                       | -   Public            |     spring            |
|                       |     tap/standpipe     |                       |
|                       |                       | -   Small water       |
|                       | -   Tube well /       |     vendor (cart with |
|                       |     borehole          |     small tank or     |
|                       |                       |     drum)             |
|                       | -   Protected dug     |                       |
|                       |     well with hand    | -   Bottled water     |
|                       |     pump              |                       |
|                       |                       | -   Tanker truck      |
|                       | -   Protected spring  |                       |
|                       |                       | -   Rainwater         |
|                       | -   Rainwater         |     collection from   |
|                       |     collection from   |     surface run off.  |
|                       |     the roof          |     Surface water     |
|                       |                       |     (river, dam,      |
|                       |                       |     lake, pond,       |
|                       |                       |     stream, canal,    |
|                       |                       |     irrigation        |
|                       |                       |     channels)         |
|                       |                       |                       |
|                       |                       | -   Protected dug     |
|                       |                       |     well with bucket  |
+-----------------------+-----------------------+-----------------------+
|- **Toilet facility    | -   Flush / pour      | -   Flush / pour      |
| type**                |     flush to piped    |     flush to          |
|                       |     sewer system or   |     elsewhere e.g. to |
|                       |     septic tank or    |     open drain        |
|                       |     pit latrine       |                       |
|                       |                       | -   Pit latrine       |
|                       | -   VIP latrine       |     without slab      |
|                       |                       |     (slab with holes) |
|                       | -   Pit latrine with  |     /open pit         |
|                       |     slab              |                       |
|                       |                       | -   Bucket            |
|                       | -   Composting toilet |                       |
|                       |                       | -   Hanging toilet /  |
|                       |                       |     hanging latrine   |
|                       |                       |                       |
|                       |                       | -   No facilities or  |
|                       |                       |     bush or field     |
+-----------------------+-----------------------+-----------------------+
|- **Garbage disposal   | -   Garbage dump      | -   In the river      |
| method**              |                       |                       |
|                       | -   Private pits      | -   On the road,      |
|                       |                       |     railway           |
|                       | -   Public pits       |     line/station      |
|                       |                       |                       |
|                       | -   Proper garbage    | -   In                |
|                       |     disposal services |     drainage/sewage/  |
|                       |                       | trench                |
|                       | -   Other organized   |                       |
|                       |     groups such as    | -   Vacant/abandoned  |
|                       |     the national      |     house/plot/field  |
|                       |     youth service     |                       |
|                       |                       | -   No designated     |
|                       |                       |     place/all over    |
|                       |                       |                       |
|                       |                       | -   Street            |
|                       |                       |     boys/urchins      |
|                       |                       |                       |
|                       |                       | -   Burning           |
|                       |                       |                       |
|                       |                       | -   Other             |
+-----------------------+-----------------------+-----------------------+


<!-- - **Lagged interviews**: Any household interview (most recent) preceding the current household interview is considered consecutive interview. In this case, only interviews in the first year (household specific) will have missing previous year. Consequently, only first year interviews will be dropped (`r percent_miss_lagged`). Not fitted. -->

## Models

- Fit two separate models
	- First (household specific) year model
	- Previous year model without first year data

**Year 1 model**

- We only have a single observation per HH. I feel we don't need a hh level random effect

	```
	model <- glmer(status ~ -1 
		+ services
		+ (ns(age, 3) 
			+ gender 
			+ slumarea 
			+ hhsize 
			+ year 
			+ ns(wealthindex, 3)
		):services 
		+ (services - 1 | hhid)
		, ...
	)
	```

**Previous year model**

	model <- glmer(status ~ -1 
		+ services
		+ (ns(age, 3) 
			+ gender 
			+ slumarea 
			+ hhsize 
			+ year 
			+ ns(wealthindex, 3) 
			+ statusP
		):services 
		+ (services - 1 | hhid)
		, ...
	)

**Interaction model**

- `wealthindex` interact with all the predictors except `hhsize`
	- The same will apply to year 1 interaction model

	```
	model <- glmer(status ~ -1 
		+ services
		+ (
			(ns(age, 3) 
				+ gender 
				+ slumarea 
				+ year 
				+ statusP
			) * ns(wealthindex, 3) 
			+ hhsize 
		):services 
		+ (services - 1 | hhid)
		, ...
	)
	```

## Results

### Year 1 model

#### Estimated effect sizes (Steve -> JD: Best description?)

- This refers to household specific first observational year

```{R}
print(y1effectsize_plot)
```

#### Predicted effects (Steve -> JD: Best description?)

```{R}
ggarrange(y1service_plot
	, y1pred_effect_plots[[1]] + rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, y1pred_effect_plots[[4]] + rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, y1pred_effect_plots[[5]]
	, y1pred_effect_plots[[6]] + rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, common.legend = TRUE
	, legend = "bottom"
	, nrow = 2
	, ncol = 3
)
```

```{R}
ggarrange(y1pred_effect_plots[[2]]
	, y1pred_effect_plots[[3]]
	, common.legend = TRUE
	, legend = "bottom"
	, nrow = 2
	, ncol = 1
)
```


### Previous year model

#### Estimated effect sizes


```{R}
print(pyreffectsize_plot)
```

#### Predicted effects (Steve -> JD: Best description?)

```{R}
ggarrange(pyrservice_plot
	, pyrpred_effect_plots[[1]] + rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, pyrpred_effect_plots[[4]] + rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, pyrpred_effect_plots[[5]]
	, pyrpred_effect_plots[[6]] + rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, common.legend = TRUE
	, legend = "bottom"
	, nrow = 2
	, ncol = 3
)
```

```{R}
ggarrange(pyrpred_effect_plots[[7]] #+ rremove("ylab") #+ rremove("y.text") + rremove("y.ticks")
	, pyrpred_effect_plots[[2]]
	, pyrpred_effect_plots[[3]]
	, nrow = 3
	, ncol = 1
)
```
